"""CrewAI tool for assembling and formatting the founder digest."""

from __future__ import annotations

from typing import Any, Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field


class DigestInput(BaseModel):
    metrics: dict = Field(description="Dict of digest metrics to format")
    date: str = Field(default="", description="Date string for the digest header")


class DigestFormatterTool(BaseTool):
    """Format operational metrics into a founder digest markdown report."""

    name: str = "format_digest"
    description: str = "Format daily operational metrics into a structured founder digest."
    args_schema: Type[BaseModel] = DigestInput

    def _run(self, metrics: dict, date: str = "") -> str:
        m = metrics

        safe_mode_flag = "🔴 SAFE MODE ACTIVE" if m.get("safe_mode_active") else "🟢 Normal Operations"
        stage2_flag = "⚠️ Stage 2 Paused" if m.get("stage2_paused") else ""
        outbound_flag = "⚠️ Outbound Pause Recommended" if m.get("outbound_pause_recommended") else ""

        flags = " | ".join(f for f in [safe_mode_flag, stage2_flag, outbound_flag] if f)

        checkout_rate = m.get("checkout_completion_rate", 0)
        activation_rate = m.get("activation_rate", 0)

        digest = f"""# RingSnap Ops Digest — {date or "Today"}

## Status: {flags}

## Funnel Summary
| Stage | Count |
|-------|-------|
| Qualified Leads | {m.get('qualified_leads', 0)} |
| Checkout Links Sent | {m.get('checkout_links_sent', 0)} |
| Checkout Completed | {m.get('checkout_completed', 0)} |
| Trials Activated | {m.get('trials_activated', 0)} |
| Activation Failures | {m.get('activation_failures', 0)} |
| Stalled Pending Signups | {m.get('stalled_pending_signups', 0)} |

## Conversion Rates
- Checkout Completion: **{checkout_rate:.0%}** (threshold: 50%)
- Trial Activation: **{activation_rate:.0%}** (threshold: 80%)

## Recovery & Safety
- Failed Recovery Attempts: {m.get('failed_recovery_count', 0)}
- Accounts Marked for Manual Review: {m.get('manual_review_count', 0)}
- Estimated Waste Prevented (no premature Stage 2): **${m.get('estimated_waste_prevented_usd', 0):.2f}**

## Ops Cost
- Total LLM Cost Today: **${m.get('total_llm_cost_usd', 0):.4f}**
- Executions by Module:
{_format_module_counts(m.get('executions_by_module', {}))}

---
*Generated by executive_digest crew. Review and forward.*
"""
        return digest


def _format_module_counts(counts: dict) -> str:
    if not counts:
        return "  _(no executions)_"
    lines = []
    for module, count in sorted(counts.items(), key=lambda x: -x[1]):
        lines.append(f"  - {module}: {count}")
    return "\n".join(lines)
